# Generated by Django 6.0.2 on 2026-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("frontend", "VLSI Frontend Design (RTL & Verification)"),
                            ("backend", "VLSI Backend Physical Design"),
                            ("sta", "Static Timing Analysis (STA)"),
                            ("analog", "Analog & Mixed Signal"),
                            ("demo", "Book Free Demo Class"),
                            ("general", "General Inquiry"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Inquiry",
                "verbose_name_plural": "Inquiries",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
