# Generated by Django 6.0.2 on 2026-03-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "course",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("frontend", "VLSI Frontend Design"),
                            ("backend", "VLSI Backend Physical Design"),
                            ("sta", "Static Timing Analysis"),
                            ("analog", "Analog & Mixed Signal"),
                            ("general", "General"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=5,
                    ),
                ),
                ("text", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
