# Generated by Django 6.0.2 on 2026-03-21 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="e.g. 'hero_bg', 'logo', 'about_img'", unique=True
                    ),
                ),
                ("image", models.ImageField(upload_to="site_images/")),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Site Image",
                "verbose_name_plural": "Site Images",
            },
        ),
    ]
