# Generated by Django 6.0.2 on 2026-03-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_siteimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteimage",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description for your own reference.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="key",
            field=models.CharField(
                choices=[
                    ("logo", "Main Logo (Navbar & Footer)"),
                    ("hero_image", "Hero Section Graphic (Homepage)"),
                    ("hero_bg", "Hero Section Background (Homepage)"),
                    ("about_image", "About Us Image (Homepage)"),
                    ("cta_bg", "Call To Action Background (Homepage)"),
                ],
                help_text="Select where this image should appear.",
                max_length=50,
                unique=True,
            ),
        ),
    ]
