# Generated by Django 6.0.2 on 2026-03-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_siteimage_description_alter_siteimage_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("digital_vlsi", "Digital VLSI Design (Homepage Card)"),
                            ("physical_design", "Physical Design (Homepage Card)"),
                            ("fpga_design", "FPGA Design (Homepage Card)"),
                            ("frontend_design", "VLSI Frontend Design (Courses Page)"),
                            (
                                "backend_design",
                                "VLSI Backend Physical Design (Courses Page)",
                            ),
                            ("sta", "Static Timing Analysis (Courses Page)"),
                            ("analog_mixed", "Analog & Mixed Signal (Courses Page)"),
                        ],
                        help_text="Select which course this image belongs to.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="course_images/")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for your reference.",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Image",
                "verbose_name_plural": "Course Images",
            },
        ),
    ]
